[package]
name = "movie_lib"
version = "0.1.0"
edition = "2021"
author  = "Suho Kwon"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
